### ISSUE TITLE
Wanna try out my project? ShaderExpo.

### ISSUE THREAD

**Issue by anuraghazra** [gkjohnson/webgl-shader-editor#5]
### ShaderExpo
WebGL Live Shader Playground.

demo: https://anuraghazra.github.io/ShaderExpo
github: https://github.com/anuraghazra/ShaderExpo

ShaderExpo is purely dependency free shader editor made in Raw WebGL API. featuring lots of cool and exciting features. 
such as
- Basic Meshes
- Texture and Custom OBJ Model Loading
- Inline Error Logs
- AutoCompletion
- Live Editing
- Export As HTML (beta)

![shaderexpo-ss](https://user-images.githubusercontent.com/35374649/55338830-1fc4f900-54bf-11e9-9143-45e11f0c91bb.png)

**Comment by gkjohnson** [comment]
Hey @anuraghazra!

I made this project with the intent of just exploring different approaches to shader debugging and otherwise haven't had a need for such a tool. But thanks!

And just a word of advice that while I always appreciate seeing what people are working on I feel it's a bit inconsiderate to advertise your project in other peoples repos. I'm always happy to receive emails if you want to share something or collaborate but I don't think this is the place for it.

Good luck with ShaderExpo!

**Comment by anuraghazra** [comment]
@gkjohnson thanks for the reply. I understand what you are saying. Actually I was just exploring hastags on GitHub then I saw this project there and I thought that my project and your project is very much similar in many ways that's why I wanted to show you my project if you are interested. I know this is a bit odd place to advertise but believe me I have no intent to advertising I am just trying to spread what I have learned. :heart: 

Btw I love open source if you can contribute please do. :+1:
